// Investigation lifecycle event types
export const INVESTIGATION_CREATED = 'INVESTIGATION_CREATED';
export const INVESTIGATION_STARTED = 'INVIGATION_STARTED';
export const INVESTIGATION_COMPLETED = 'INVESTIGATION_COMPLETED';
export const INVESTIGATION_CANCELLED = 'INVESTIGATION_CANCELLED';
export const INVESTIGATION_ARCHIVED = 'INVESTIGATION_ARCHIVED';
export const INVESTIGATION_RESTORED = 'INVESTIGATION_RESTORED';
export const INVESTIGATION_DELETED = 'INVESTIGATION_DELETED';
export const INVESTIGATION_RENAMED = 'INVESTIGATION_RENAMED';
export const INVESTIGATION_PINNED = 'INVIGATION_PINNED';
export const INVESTIGATION_UNPINNED = 'INVESTIGATION_UNPINNED';

