// client/src/shared/lib/persistence/persistenceEvents.js
export const INVESTIGATION_SAVED = 'INVESTIGATION_SAVED';
export const INVESTIGATION_LOADED = 'INVESTIGATION_LOADED';
export const INVESTIGATION_DELETED = 'INVESTIGATION_DELETED';
export const INVESTIGATION_ARCHIVED = 'INVESTIGATION_ARCHIVED';
export const INVESTIGATION_RESTORED = 'INVESTIGATION_RESTORED';
