const { InvestigationPlan } = require('../domain/plan');

/**
 * PlanValidator
 * 
 * Ensures the raw JSON generated by the LLM strictly conforms to the InvestigationPlan schema
 * and contains valid data before the ExecutionEngine touches it.
 */
class PlanValidator {
  /**
   * Validates and parses the raw JSON.
   * 
   * @param {string} rawJson 
   * @returns {InvestigationPlan}
   */
  validate(rawJson) {
    let parsed;
    try {
      parsed = JSON.parse(rawJson);
    } catch (err) {
      throw new Error(`Plan Validation Failed: Invalid JSON. Details: ${err.message}`);
    }

    // 1. Check required top-level fields
    if (!parsed.mission || typeof parsed.mission !== 'string') {
      throw new Error('Plan Validation Failed: Missing or invalid "mission" field');
    }
    if (!parsed.hypothesis || typeof parsed.hypothesis !== 'string') {
      throw new Error('Plan Validation Failed: Missing or invalid "hypothesis" field');
    }
    if (typeof parsed.confidence !== 'number' || parsed.confidence < 0 || parsed.confidence > 1) {
      throw new Error('Plan Validation Failed: "confidence" must be a number between 0.0 and 1.0');
    }

    // 2. Check executionSteps
    if (!parsed.executionSteps) {
      parsed.executionSteps = [];
    }
    
    if (!Array.isArray(parsed.executionSteps)) {
      throw new Error('Plan Validation Failed: "executionSteps" must be an array');
    }
    
    if (parsed.executionSteps.length === 0 && !parsed.isResolved) {
      throw new Error('Plan Validation Failed: "executionSteps" must be a non-empty array unless "isResolved" is true');
    }

    for (let i = 0; i < parsed.executionSteps.length; i++) {
      const step = parsed.executionSteps[i];
      if (!step.action || (step.action !== 'read' && step.action !== 'jump')) {
        throw new Error(`Plan Validation Failed: Step ${i} has invalid action "${step.action}"`);
      }
      if (!step.target || typeof step.target !== 'string') {
        throw new Error(`Plan Validation Failed: Step ${i} missing "target" file path`);
      }
      if (!step.reason || typeof step.reason !== 'string') {
        throw new Error(`Plan Validation Failed: Step ${i} missing "reason"`);
      }
    }

    // Return the validated model object
    return new InvestigationPlan(parsed);
  }
}

module.exports = { PlanValidator };
