const { InvestigationPlan } = require('../domain/plan');

/**
 * PlanValidator
 * 
 * Ensures the raw JSON generated by the LLM strictly conforms to the InvestigationPlan schema
 * and contains valid data before the ExecutionEngine touches it.
 */
class PlanValidator {
  /**
   * Validates and parses the raw JSON.
   * 
   * @param {string} rawJson 
   * @param {string} contextStr
   * @returns {InvestigationPlan}
   */
  validate(rawJson, contextStr = '') {
    let parsed;
    try {
      parsed = JSON.parse(rawJson);
    } catch (err) {
      throw new Error(`Plan Validation Failed: Invalid JSON. Details: ${err.message}`);
    }

    // 1. Check required top-level fields
    if (!parsed.mission || typeof parsed.mission !== 'string') {
      throw new Error('Plan Validation Failed: Missing or invalid "mission" field');
    }
    if (!parsed.hypothesis || typeof parsed.hypothesis !== 'string') {
      throw new Error('Plan Validation Failed: Missing or invalid "hypothesis" field');
    }
    if (typeof parsed.confidence !== 'number' || parsed.confidence < 0 || parsed.confidence > 1) {
      throw new Error('Plan Validation Failed: "confidence" must be a number between 0.0 and 1.0');
    }
    if (parsed.isResolved !== undefined && typeof parsed.isResolved !== 'boolean') {
      throw new Error('Plan Validation Failed: "isResolved" must be a boolean');
    }
    
    // Explicitly enforce boolean false if missing or undefined
    parsed.isResolved = parsed.isResolved === true;

    // Extract valid paths from context
    const validPaths = new Set();
    const regex = /FILE PATH: ([^\n]+)/g;
    let match;
    while ((match = regex.exec(contextStr)) !== null) {
      validPaths.add(match[1].trim());
    }

    // Validate consultedFiles
    if (Array.isArray(parsed.consultedFiles)) {
      parsed.consultedFiles = parsed.consultedFiles.filter(f => {
        if (!f.path || typeof f.path !== 'string') return false;
        if (!f.reason || typeof f.reason !== 'string') return false;
        
        // Ensure path exists in context to prevent LLM hallucination
        if (!validPaths.has(f.path)) {
          console.warn(`[PlanValidator] Filtered out invented consultedFile path: ${f.path}`);
          return false;
        }
        return true;
      });
    } else {
      parsed.consultedFiles = [];
    }

    // 2. Check executionSteps
    if (!parsed.executionSteps) {
      parsed.executionSteps = [];
    }
    
    if (!Array.isArray(parsed.executionSteps)) {
      throw new Error('Plan Validation Failed: "executionSteps" must be an array');
    }
    
    if (parsed.executionSteps.length === 0 && !parsed.isResolved) {
      throw new Error('Plan Validation Failed: "executionSteps" must be a non-empty array unless "isResolved" is true. The AI failed to determine the next steps.');
    }

    for (let i = 0; i < parsed.executionSteps.length; i++) {
      const step = parsed.executionSteps[i];
      if (!step.action || (step.action !== 'read' && step.action !== 'jump')) {
        throw new Error(`Plan Validation Failed: Step ${i} has invalid action "${step.action}"`);
      }
      if (!step.target || typeof step.target !== 'string') {
        throw new Error(`Plan Validation Failed: Step ${i} missing "target" file path`);
      }
      if (!step.reason || typeof step.reason !== 'string') {
        throw new Error(`Plan Validation Failed: Step ${i} missing "reason"`);
      }
    }

    // Return the validated model object
    return new InvestigationPlan(parsed);
  }
}

module.exports = { PlanValidator };
